import type { ClassifiedRoute } from "@/lib/core";
import { actionableRoutes, parameterLines, type GenerateOptions } from "./shared";

export function generateLlmsTxt(
  routes: ClassifiedRoute[],
  options: GenerateOptions,
): string {
  const actions = actionableRoutes(routes);
  const lines = [
    `# ${options.title}`,
    "",
    `> ${options.description ?? "Auto-generated by AgentReady so AI agents can use this app's HTTP APIs."}`,
    "",
    "This file lists callable actions extracted from the project's Next.js API routes.",
    "",
    "## Actions",
    "",
  ];

  if (actions.length === 0) {
    lines.push("- No callable API routes were found.");
    lines.push("");
    return lines.join("\n");
  }

  for (const route of actions) {
    const params = parameterLines(route.parameters);
    const review =
      route.classification_status === "unclassified" ? " Needs review." : "";
    const paramSuffix = params ? ` Params: ${params}.` : "";
    lines.push(
      `- [${route.action_name}](${route.path}): ${route.method}. ${route.description}${paramSuffix}${review}`,
    );
  }

  lines.push("");
  return lines.join("\n");
}
