import type { ClassifiedRoute } from "@/lib/core";
import { actionableRoutes, uniqueToolName, type GenerateOptions } from "./shared";

export type McpTool = {
  name: string;
  description: string;
  inputSchema: {
    type: "object";
    properties: Record<string, { type: string; description: string }>;
    required: string[];
  };
  metadata: {
    method: string;
    path: string;
  };
};

export function generateMcpTools(
  routes: ClassifiedRoute[],
): { tools: McpTool[] } {
  const used = new Set<string>();
  const tools = actionableRoutes(routes).map((route) => {
    const name = uniqueToolName(route, used);
    const properties: McpTool["inputSchema"]["properties"] = {};
    const required: string[] = [];
    for (const param of route.parameters) {
      properties[param.name] = {
        type: "string",
        description: `${param.in} parameter`,
      };
      if (param.required) {
        required.push(param.name);
      }
    }
    return {
      name,
      description: `${route.method} ${route.path} — ${route.description}`,
      inputSchema: {
        type: "object" as const,
        properties,
        required,
      },
      metadata: {
        method: route.method,
        path: route.path,
      },
    };
  });
  return { tools };
}

export function generateMcpToolsJson(routes: ClassifiedRoute[]): string {
  return `${JSON.stringify(generateMcpTools(routes), null, 2)}\n`;
}

export function generateMcpServer(
  routes: ClassifiedRoute[],
  options: GenerateOptions,
): string {
  const { tools } = generateMcpTools(routes);
  return `#!/usr/bin/env node
/**
 * Generated by AgentReady for ${options.title}.
 * Run: BASE_URL=https://your-app.example node mcp-server.mjs
 */
const BASE_URL = (process.env.BASE_URL || "http://localhost:3000").replace(/\\/$/, "");
const tools = ${JSON.stringify(tools, null, 2)};

function applyPath(path, args) {
  return path
    .replace(/\\[\\[?\\.\\.\\.([^\\]]+)\\]\\]?/g, (_, name) => encodeURIComponent(String(args[name] ?? "")))
    .replace(/\\[([^\\]]+)\\]/g, (_, name) => encodeURIComponent(String(args[name] ?? "")));
}

async function callTool(name, args = {}) {
  const tool = tools.find((item) => item.name === name);
  if (!tool) {
    throw new Error("Unknown tool: " + name);
  }
  const url = new URL(applyPath(tool.metadata.path, args), BASE_URL);
  const body = {};
  for (const [key, value] of Object.entries(args)) {
    const schema = tool.inputSchema.properties[key];
    if (!schema) continue;
    if (schema.description.startsWith("query")) {
      url.searchParams.set(key, String(value));
    } else if (schema.description.startsWith("body")) {
      body[key] = value;
    }
  }
  const init = { method: tool.metadata.method, headers: { "content-type": "application/json" } };
  if (tool.metadata.method !== "GET" && tool.metadata.method !== "HEAD" && Object.keys(body).length > 0) {
    init.body = JSON.stringify(body);
  }
  const response = await fetch(url, init);
  const text = await response.text();
  return { status: response.status, body: text };
}

async function handle(message) {
  if (message.method === "initialize") {
    return {
      protocolVersion: "2024-11-05",
      serverInfo: { name: ${JSON.stringify(options.title)}, version: "0.2.0" },
      capabilities: { tools: {} },
    };
  }
  if (message.method === "tools/list") {
    return { tools: tools.map(({ metadata, ...tool }) => tool) };
  }
  if (message.method === "tools/call") {
    const result = await callTool(message.params?.name, message.params?.arguments ?? {});
    return { content: [{ type: "text", text: JSON.stringify(result) }] };
  }
  if (message.method === "notifications/initialized") {
    return null;
  }
  throw new Error("Unsupported method: " + message.method);
}

let buffer = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", async (chunk) => {
  buffer += chunk;
  let index;
  while ((index = buffer.indexOf("\\n")) >= 0) {
    const line = buffer.slice(0, index).trim();
    buffer = buffer.slice(index + 1);
    if (!line) continue;
    const message = JSON.parse(line);
    try {
      const result = await handle(message);
      if (result && message.id !== undefined) {
        process.stdout.write(JSON.stringify({ jsonrpc: "2.0", id: message.id, result }) + "\\n");
      }
    } catch (error) {
      process.stdout.write(
        JSON.stringify({
          jsonrpc: "2.0",
          id: message.id,
          error: { code: -32000, message: error instanceof Error ? error.message : String(error) },
        }) + "\\n",
      );
    }
  }
});
`;
}
